version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.response.dev
    image: response
    container_name: response
    entrypoint: bash
    command: /app/demo/startup-dev.sh
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file: demo/.env-dev

    stdin_open: true
    tty: true

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

