FROM python:3.12-slim-bullseye AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
COPY /demo/requirements-prod.txt /app
COPY /demo/startup-prod.sh .
RUN pip install -r requirements-prod.txt

RUN mkdir -p /app/demo/demo/database

COPY . /app/

ENTRYPOINT [ "/app/demo/startup-prod.sh" ]