# Generated by Django 4.2.7 on 2023-12-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0017_externaluser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to='response.externaluser'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='summary',
            field=models.TextField(blank=True, help_text='Can you share any useful details?', null=True),
        ),
    ]
