# Generated by Django 4.2.7 on 2023-12-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0018_incident_updated_by_alter_incident_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Issue updated by?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by', to='response.externaluser'),
        ),
    ]
