# Generated by Django 4.2.7 on 2023-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0019_alter_incident_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='status_update',
            field=models.TextField(blank=True, help_text='Can you share any useful details?', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='status_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
