# Generated by Django 4.2.7 on 2023-12-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0020_incident_status_update_incident_status_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='status_update_time',
        ),
        migrations.AddField(
            model_name='incident',
            name='status_update_last',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status_update',
            field=models.TextField(blank=True, help_text='Can you provide a status update?', null=True),
        ),
    ]
