# Generated by Django 4.2.7 on 2024-01-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0022_incident_status_update_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='done_date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='action',
            name='type',
        ),
    ]
