# Generated by Django 4.2.7 on 2024-01-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0024_remove_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.externaluser'),
        ),
    ]
