# Generated by Django 4.2.7 on 2024-01-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0025_action_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to='response.externaluser'),
        ),
    ]
