# Generated by Django 4.2.7 on 2024-01-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0028_alter_action_assigned_to_alter_action_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_by', to='response.externaluser'),
        ),
    ]
