# Generated by Django 4.2.7 on 2024-01-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0029_action_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to='response.externaluser'),
        ),
    ]
