version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.response.prod
    image: response
    container_name: response
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      POSTGRES: "true"
    env_file: .env-prod
    volumes:
      - ./:/app
      - ../:/response
      - pypd:/app/pypd
      - static_volume:/home/app/web/staticfiles
    stdin_open: true
    tty: true
  
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - response
    ports:
      - "8080:80"

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

  db:
    image: "postgres:16.0"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example    
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  pypd:
  static_volume:
