version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.response.dev
    image: response
    container_name: response
    entrypoint: bash
    command: /app/startup-dev.sh
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    environment:
      POSTGRES: "true"
    env_file: .env-dev
    volumes:
      - ./:/app
      - ../:/response
      - pypd:/app/pypd
    stdin_open: true
    tty: true

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

  db:
    image: "postgres:16.0"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  pypd:
