FROM python:3.7-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements-prod.txt /app
COPY ./startup-prod.sh .
RUN pip install -r requirements-prod.txt

COPY . /app/

ENTRYPOINT [ "/app/startup-prod.sh" ]